import Test.DocTest

main :: IO ()
main = doctest
  [ "-isrc"
  , "src/"
  , "-XDeriveFunctor"
  , "-XDeriveFoldable"
  , "-XDeriveTraversable"
  , "-XDeriveGeneric"
  , "-XDeriveDataTypeable"
  , "-XDerivingStrategies"
  , "-XGeneralisedNewtypeDeriving"
  , "-XGADTs"
  , "-XDataKinds"
  , "-XRankNTypes"
  , "-XPolyKinds"
  , "-XKindSignatures"
  , "-XTypeOperators"
  , "-XMultiParamTypeClasses"
  , "-XFunctionalDependencies"
  , "-XFlexibleInstances"
  , "-XFlexibleContexts"
  , "-XDerivingVia"
  , "-XLambdaCase"
  , "-XPatternSynonyms"
  , "-XViewPatterns"
  , "-XStandaloneDeriving"
  , "-XTypeFamilies"
  , "-XTypeApplications"
  , "-XScopedTypeVariables"
  , "-XTupleSections"
  , "-XApplicativeDo"
  , "-XInstanceSigs"
  , "-XBlockArguments"
  , "-XQuantifiedConstraints"
  , "-XBangPatterns"
  ]
